### ISSUE TITLE
create hero section

### ISSUE THREAD

**Issue by serikovlearning** [qase-tms/shelterpaws#39]
[Design](https://www.figma.com/file/vPsA8xRIe0BgYkYPDIt8gw/Shelterpaws?type=design&node-id=2-433&mode=design&t=G23yg8I2Qq10CV8J-4)

**Comment by serikovlearning** [comment]
Make adaptive layout at the discretion of the developer

**Comment by Andrenord282** [comment]
I would like to take this task when it's available
