### ISSUE TITLE
create about the shelter section

### ISSUE THREAD

**Issue by serikovlearning** [qase-tms/shelterpaws#40]
[Design](https://www.figma.com/file/vPsA8xRIe0BgYkYPDIt8gw/Shelterpaws?type=design&node-id=2-659&mode=design&t=G23yg8I2Qq10CV8J-4)

- [ ] Add ui-component `section-header` https://prnt.sc/Jp1ZQIcwlu3J
- [ ] Add ui-component `responsive-video`
- [ ] Adaptive from 320px

**Comment by serikovlearning** [comment]
Make adaptive layout at the discretion of the developer

**Comment by Salexg34** [comment]
I'm ready to take on the task of creating a section About the shelter
