### ISSUE TITLE
create icon ui-component

### ISSUE THREAD

**Issue by Christik** [qase-tms/shelterpaws#54]
- [x] The component takes the type as a parameter. Example: `{{ icon(type='phone')}}`
- [x] Add all types from figma: `donate`, `phone`, `pin`, `email`
- [x] Icon image should be `<svg>` tag
- [x] The icon can be any color. Add an optional color parameter. Possible values: `accent`, `inverse`,` secondary-inverse`. Default color: black
- [ ] Add icon to button 
- [x] Add all icons to ui page

**Comment by Tabarzin** [comment]
Я взял.
