### ISSUE TITLE
multiple frontend fixes

### ISSUE THREAD

**Issue by sharovatov** [qase-tms/shelterpaws#79]
### main page 

- [x] change the title from "Territory Of Goodness" to "The territory of good"
- [x] change "Let's Help Pets" to "Stray animals shelter"
- [x] change "Lorem ipsum dolor sit amet, consectetur adipiscing elit." to "We're helping 53 stray dogs and 2 cats"

### about the shelter section

- [x] change long `"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus convallis iaculis. Maecenas augue justo, mattis at felis quis, molestie fermentum magna. Ut mi ipsum, tempor in molestie ac, sollicitudin at ex. Sed mollis orci sed nulla vehicula, et malesuada diam condimentum. Nullam eu maximus magna. Quisque urna diam, sodales non dolor a, pharetra tempus arcu. Sed mauris lacus, maximus at velit vel, commodo luctus tortor."` **to** `We are raising funds to support animal welfare in and around Poti, Georgia. Sadly, this region is severely lacking in animal shelters and rescuers, leaving countless stray animals to fend for themselves in the streets. My husband and I started building the Territory of Good shelter from the ground up after bringing 15 strays from Ukraine. Our ever-growing shelter is supported only by our single income and the generosity of other animal lovers.
Donated funds are used to build additional enclosures for our animals, pay for much-needed veterinary care, find forever homes for our animals, and cover the costs of essentials such as food, enrichment toys, and bedding.
Every donation helps us improve the quality of life for animals in our community. We strive to save as many strays as we can — especially old, injured, or otherwise high-risk animals. Your donations help us care for animals recovering from abuse, neglect, and illness and give them a second chance at life`

- [x] change **44 котёнка** video embed to `<iframe width="780" height="441" src="https://www.youtube.com/embed/BruIX11Qo1w?list=PLt75o-m3IfmyMXeqT7BpwB6x7GRrti9l5" title="Meet Irina, owner of Territory of Good animal shelter" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`
- [x] change img with `https://td.shelterpaws.org/static/img/upload/shelter.jpg` src to 
`http://sharovatov.github.io/files/irina.png`

### contact us section
- [x] change two telephones "+7 987 654 32 10 and +3 123 456 789" to just one "+995 557 36 66 74"
- [x] change the email address to "vitaly.sharovatov@gmail.com" — I still haven't connected google mail to shelterpaws

### final touches

- [x] remove "main", "contacts", "donations" and "adopted" buttons on the top
- [x] when any of the "donate" buttons on the page is clicked, scroll to the very bottom where the contacts are shown now
- [x] in the contacts section below the phones add "To donate via paypal, please send money to Petr’s account: pereborschikovpetr@gmail.com"

**Comment by Andrenord282** [comment]
done
